// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUqWHVj6blXHD0QWpVPGwn_QjDg7wnHM',
    appId: '1:872255766559:web:e5b583687d834d6679d52a',
    messagingSenderId: '872255766559',
    projectId: 'runner-fcaf6',
    authDomain: 'runner-fcaf6.firebaseapp.com',
    storageBucket: 'runner-fcaf6.appspot.com',
    measurementId: 'G-YCV6HD18Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbh0LG8hLU-piGhnUMQ3IetQ7ItrVtBeg',
    appId: '1:872255766559:android:265e93be07a2440579d52a',
    messagingSenderId: '872255766559',
    projectId: 'runner-fcaf6',
    storageBucket: 'runner-fcaf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DsrYOLUiQFmbfqy-3LYRBpTpLmmCF6M',
    appId: '1:872255766559:ios:77cd9dfea425131a79d52a',
    messagingSenderId: '872255766559',
    projectId: 'runner-fcaf6',
    storageBucket: 'runner-fcaf6.appspot.com',
    iosBundleId: 'com.example.runner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DsrYOLUiQFmbfqy-3LYRBpTpLmmCF6M',
    appId: '1:872255766559:ios:77cd9dfea425131a79d52a',
    messagingSenderId: '872255766559',
    projectId: 'runner-fcaf6',
    storageBucket: 'runner-fcaf6.appspot.com',
    iosBundleId: 'com.example.runner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBUqWHVj6blXHD0QWpVPGwn_QjDg7wnHM',
    appId: '1:872255766559:web:17da9d8000271d8679d52a',
    messagingSenderId: '872255766559',
    projectId: 'runner-fcaf6',
    authDomain: 'runner-fcaf6.firebaseapp.com',
    storageBucket: 'runner-fcaf6.appspot.com',
    measurementId: 'G-HKWRBM0DCZ',
  );
}
